name: deft

packages:
  - pkg/*

scripts:
  analyze:
    exec: dart analyze .
  format:
    exec: dart format .
  test:
    exec: dart test .
  get:
    exec: dart pub get
  outdated:
    exec: dart pub outdated
  upgrade:
    exec: dart pub upgrade