name: deft_client_common
description: Shared utilities and middleware for gRPC clients.
version: 0.2.0
repository: https://github.com/mockturtl/deft/tree/master/pkg/client_common

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.0
  protobuf: ^2.1.0
  grpc: ^3.1.0

  # Careful! Flutter pins these packages.
  # <https://github.com/flutter/flutter/blob/stable/packages/flutter/pubspec.yaml>
  collection: ^1.17.1
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.4
  http2: ^2.0.1
  mockito: ^5.4.0
  tidy: ^3.0.0
  test: ^1.23.1

dependency_overrides:
  grpc: # https://github.com/grpc/grpc-dart/issues/548
    git:
      url: https://github.com/mockturtl/grpc-dart
      ref: 3.1.0+pr-548