name: deft_client_common
description: Shared utilities and middleware for gRPC clients.
version: 0.3.0
repository: https://github.com/mockturtl/deft/tree/master/pkg/client_common

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  protobuf: ^3.0.0
  grpc: ^3.2.2

  # Careful! Flutter pins these packages.
  # <https://github.com/flutter/flutter/blob/stable/packages/flutter/pubspec.yaml>
  collection: ^1.17.1
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.5
  http2: ^2.1.0
  mockito: ^5.4.2
  tidy: ^3.0.0
  test: ^1.24.3

dependency_overrides:
  grpc: # https://github.com/grpc/grpc-dart/issues/548
    git:
      url: https://github.com/mockturtl/grpc-dart
      ref: v3.2.2+pr-548