name: deft_logging
description: Logging adapters for the Deft framework.
version: 0.1.0
repository: https://github.com/mockturtl/deft/tree/master/pkg/logging

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  googleapis: ^11.1.0
  googleapis_auth: ^1.4.0
  grpc: ^3.1.0
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.4
  mockito: ^5.4.0
  test: ^1.23.1
  tidy: ^3.0.0
