name: deft_logging
description: Logging adapters for the Deft framework.
version: 0.3.0
repository: https://github.com/mockturtl/deft/tree/master/pkg/logging

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  googleapis: ^11.2.0
  googleapis_auth: ^1.4.1
  grpc: ^3.2.2
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.5
  mockito: ^5.4.2
  test: ^1.24.3
  tidy: ^3.0.0
