name: deft_logging
description: Logging adapters.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  googleapis: ^10.1.0
  googleapis_auth: ^1.4.0
  grpc: ^3.1.0
  meta: ^1.9.0

dev_dependencies:
  build_runner: ^2.3.3
  mockito: ^5.3.2
  test: ^1.23.1
  tidy: ^2.19.0
