name: deft_client_common
description: Shared utilities and middleware for gRPC clients.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  args: ^2.4.0
  protobuf: ^2.1.0
  grpc: ^3.1.0

  # Careful! Flutter pins these packages.
  # <https://github.com/flutter/flutter/blob/stable/packages/flutter/pubspec.yaml>
  collection: ^1.17.0
  meta: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  http2: ^2.0.1
  mockito: ^5.3.2
  tidy: ^2.19.0
  test: ^1.23.1

dependency_overrides:
  grpc: # https://github.com/grpc/grpc-dart/issues/548
    git:
      url: https://github.com/mockturtl/grpc-dart
      ref: 3.1.0+pr-548